### ISSUE TITLE
Error: 'severityLevel' has incomplete type

### ISSUE THREAD

**Issue by CMDR-Piboy314** [ConstellationGamesOrg/Constellation-Engine#6]
After the logging update, this error occurs
`src/logger.c:43:71: error: type of formal parameter 2 is incomplete
   43 | intf("%s : %s\n", logger_logSeverityToColor(loggerInstance, severityLevel), message)`
`src/logger.c:59:104: error: parameter 2 (‘severityLevel’) has incomplete type
   59 | er_loggerOptions* loggerInstance, enum logger_SeverityLevel severityLevel) {`

**Comment by CMDR-JohnAlex** [comment]
So when compiling with g++ I get no errors but gcc does get errors. Using replit I think I found a fix, I'm just testing it now.

**Comment by CMDR-Piboy314** [comment]
Issue does not persist, thank you!
